export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const PROFIL_USER = "PROFIL_USER";
export const PROFIL_USER_SUCCESS = "PROFIL_USER_SUCCESS";
export const PROFIL_USER_FAIL = "PROFIL_USER_FAIL";

export const ADDUSER_POSTS = "USER_POSTS";
export const ADDUSER_POSTS_SUCCESS = "USER_POSTS_SUCCESS";
export const ADDUSER_POSTS_FAIL = "USER_POSTS_FAIL";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const GETUSER_POSTS = "GETUSER_POSTS";
export const GETUSER_POSTS_SUCCESS = "GETUSER_POSTS_SUCCESS";
export const GETUSER_POSTS_FAIL = "GETUSER_POSTS_FAIL";

export const DELETEONE_POST = "DELETEONE_POST";
export const DELETEONE_POST_SUCCESS = "DELETEONE_POST_SUCCESS";
export const DELETEONE_POST_FAIL = "DELETEONE_POST_FAIL";

export const GETALL_POSTS = "GETALL_POSTS";
export const GETALL_POSTS_SUCCESS = "GETALL_POSTS_SUCCESS";
export const GETALL_POSTS_FAIL = "GETALL_POSTS_FAIL";

export const REGISTER_AGENCE = "REGISTER_AGENCE";
export const REGISTER_AGENCE_SUCCESS = "REGISTER_AGENCE_SUCCESS";
export const REGISTER_AGENCE_FAIL = "REGISTER_AGENCE_FAIL";

export const LOGIN_AGENCE = "LOGIN_AGENCE";
export const LOGIN_AGENCE_SUCCESS = "LOGIN_AGENCE_SUCCESS";
export const LOGIN_AGENCE_FAIL = "LOGIN_AGENCE_FAIL";

export const LOGOUT_AGENCE = "LOGOUT_AGENCE";
export const LOGOUT_AGENCE_SUCCESS = "LOGOUT_AGENCE_SUCCESS";
export const LOGOUT_AGENCE_FAIL = "LOGOUT_AGENCE_FAIL";

export const PROFIL_AGENCE = "PROFIL_AGENCE";
export const PROFIL_AGENCE_SUCCESS = "PROFIL_AGENCE_SUCCESS";
export const PROFIL_AGENCE_FAIL = "PROFIL_AGENCE_FAIL";

export const ADD_OFFRE = 'ADD_OFFRE';
export const ADD_OFFRE_SUCCESS = 'ADD_OFFRE_SUCCESS';
export const ADD_OFFRE_FAIL = 'ADD_OFFRE_FAIL';

export const GET_ALLOFFRES = 'GET_ALLOFFRES';
export const GET_ALLOFFRES_SUCCESS = 'GET_ALLOFFRES_SUCCESS';
export const GET_ALLOFFRES_FAIL = 'GET_ALLOFFRES_FAIL';

export const DELETE_OFFRE = 'DELETE_OFFRE';
export const DELETE_OFFRE_SUCCESS = 'DELETE_OFFRE_SUCCESS';
export const DELETE_OFFRE_FAIL = 'DELETE_OFFRE_FAIL';

export const GET_ALLUSERS = 'GET_ALLUSERS';
export const GET_ALLUSERS_SUCCESS = 'GET_ALLUSERS_SUCCESS';
export const GET_ALLUSERS_FAIL = 'GET_ALLUSERS_FAIL';

export const GET_ALLAGENCES = 'GET_ALLAGENCES';
export const GET_ALLAGENCES_SUCCESS = 'GET_ALLAGENCES_SUCCESS';
export const GET_ALLAGENCES_FAIL = 'GET_ALLAGENCES_FAIL';

export const ADD_ADMIN = 'ADD_ADMIN';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_FAIL = 'ADD_ADMIN_FAIL';

export const BAN_USER = 'BAN_USER';
export const BAN_USER_SUCCESS = 'BAN_USER_SUCCESS';
export const BAN_USER_FAIL = 'BAN_USER_FAIL';

export const BAN_AGENCE = 'BAN_AGENCE';
export const BAN_AGENCE_SUCCESS = 'BAN_AGENCE_SUCCESS';
export const BAN_AGENCE_FAIL = 'BAN_AGENCE_FAIL';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const DELETE_AGENCE = 'DELETE_AGENCE';
export const DELETE_AGENCE_SUCCESS = 'DELETE_AGENCE_SUCCESS';
export const DELETE_AGENCE_FAIL = 'DELETE_AGENCE_FAIL';

export const GETAGENCES_USER = 'GETAGENCES_USER';
export const GETAGENCES_USER_SUCCESS = 'GETAGENCES_USER_SUCCESS';
export const GETAGENCES_USER_FAIL = 'GETAGENCES_USER_FAIL';

export const GETOFFRES_USER ='GETOFFRES_USER';
export const GETOFFRES_USER_SUCCESS ='GETOFFRES_USER_SUCCESS';
export const GETOFFRES_USER_FAIL ='GETOFFRES_USER_FAIL';

export const GETAGENCEUSER_OFFRES = 'GETAGENCEUSER_OFFRES';
export const GETAGENCEUSER_OFFRES_SUCCESS = 'GETAGENCEUSER_OFFRES_SUCCESS';
export const GETAGENCEUSER_OFFRES_FAIL = 'GETAGENCEUSER_OFFRES_FAIL';

export const NOTATE_AGENCE = 'NOTATE_AGENCE';
export const NOTATE_AGENCE_SUCCESS = 'NOTATE_AGENCE_SUCCESS';
export const NOTATE_AGENCE_FAIL = 'NOTATE_AGENCE_FAIL';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

export const UNLIKE_POST = 'UNLIKE_POST';
export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS';
export const UNLIKE_POST_FAIL = 'UNLIKE_POST_FAIL';

export const LIKE_OFFRE = 'LIKE_OFFRE';
export const LIKE_OFFRE_SUCCESS = 'LIKE_OFFRE_SUCCESS';
export const LIKE_OFFRE_FAIL = 'LIKE_OFFRE_FAIL';

export const UNLIKE_OFFRE = 'UNLIKE_OFFRE';
export const UNLIKE_OFFRE_SUCCESS = 'UNLIKE_OFFRE_SUCCESS';
export const UNLIKE_OFFRE_FAIL = 'UNLIKE_OFFRE_FAIL';

export const HOME_AGENCES ='HOME_AGENCES';
export const HOME_AGENCES_SUCCESS ='HOME_AGENCES_SUCCESS';
export const HOME_AGENCES_FAIL ='HOME_AGENCES_FAIL';

export const HOME_OFFRES ='HOME_OFFRES';
export const HOME_OFFRES_SUCCESS ='HOME_OFFRES_SUCCESS';
export const HOME_OFFRES_FAIL ='HOME_OFFRES_FAIL';
